
# 通知メッセージの ON/OFF
# 権限 combakme.disable-notify があるプレイヤーに対しては送信しません
enable-messages: true

# 各時間ごとにメッセージの内容を設定できます
messages:
  - schedule-time: 12h0m  # 最終ログインから12時間0分
    contents:  # ランダムで送信する内容を決定します
      - "サーバーをログアウトしてから１２時間経過しました"

  - schedule-time: 12h0m,30m  # 最終ログインから12時間0分から12時間30分の間に1回
    contents:
      - "やり残したことはありませんか？"

  - schedule-time: 24h  # 最終ログインから24時間0分 (0分は省略可)
    contents:
      - "サーバーをログアウトしてから２４時間経過しました"

  - schedule-time: 24h,-30m  # 最終ログインから24時間0分から47時間30分の間に1回 (負の値で次回の通知時間から計算 ※範囲を考慮しない)
    contents:
      - "今日も参加しませんか？"

  - schedule-time: 48h
    contents:
      - "サーバーをログアウトしてから４８時間経過しました"

  - schedule-time: 48h,30m
    contents:
      - "今日も参加しませんか？"

# 通常の messages 設定にある経過時間を超えた後のメッセージ設定 (繰り返し)
message-2:
  enable: false
  timer-time: 0m,15m
  contents: []


# データベース設定
database:
  type: mysql  # 現在は mysql のみ
  mysql:
    username: root
    password: "password"
    address: localhost:3306
    database: "combakme"
    options:
      autoReconnect: true
