name: CombakMe
version: '${version}'
main: com.gmail.necnionch.myplugin.combakme.bukkit.CombakMePlugin
api-version: '1.13'
author: Necnion8
website: https://github.com/Necnion8/CombakMe

depend:
  - DiscordSRV

softdepend:
  - Vault

permissions:
  combakme.disable-notify:
    description: "この権限があるプレイヤーに対しては通知メッセージを送信しません"
